name: Continuous Integration Github Action

on:
  push:
  pull_request:
jobs:
  run-static-codebase-analysis:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm i 
      - name: Run linter
        run: npm run lint
      - name: Run formater
        run: npm run format
      - name: Run type-checker
        run: npm run type-checker
        
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Run test suite
        run: npm run test
      - name: Install playwright browser
        run: npx playwright install --with-deps
      - name: Run e2e test
        run: npm run e2e

  